version: 1.0.{build}

image: Ubuntu

install:
  - npm install

build_script:
  - npm run build

artifacts:
  - path: dist
    name: build

deploy_script:
  - npm install -g gh-pages
  - gh-pages -d dist
